version: '3.9'

services:
  client:
    image: epark0120/devspace-client:dev
    pull_policy: always
    ports:
      - "3000:3000"
  server:
    image: epark0120/devspace-server:dev
    pull_policy: always
    ports:
      - "8080:8080"
    command: java -jar app/app.jar